[build]
builder = "nixpacks"
buildCommand = "npm install"
watchPatterns = ["Backend/**"]

[deploy]
startCommand = "node app.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "3000" 